### ISSUE TITLE
How to Extract CSI from Argos Open Dataset Files?

### ISSUE THREAD

**Issue by xuanyv** [mobicom24/RF-Diffusion#12]
Hello,

I am working with the Argos open dataset, specifically the file named `ArgosCSI-8x4-2015-12-18-22-17-57_good_uhfstatic_vito_2omni_2directionalpolarized.hdf5`. I would like to know the correct method to extract CSI (Channel State Information) from this dataset file.

So far, I have identified the following datasets within the file:
- `FrameCompleteTime`
- `Pilot_Samples`
- `RSSI`
- `mob_tx_gain`

Could you please guide me on which dataset contains the CSI data and the steps required to correctly extract and interpret it?

Thank you for your help!

**Comment by mobicom24** [comment]
Of course!

We use the ```samps2csi``` function provided in the [RENEWLab GitHub repository](https://github.com/renew-wireless/RENEWLab/blob/master/PYTHON/IrisUtils/hdf5_lib.py), specifically found on line 287 of the ```hdf5_lib.py``` file. This function allows you to extract the CSI (Channel State Information) from the raw data stored in the HDF5 format.

I hope this helps you!

**Comment by xuanyv** [comment]
Thank you very much for your answer. This function indeed can convert the raw HDF5 data into CSI, but how should parameters like polit_f and fft_size be obtained? I am new to this field and would greatly appreciate your guidance. If you could provide the processing code, that would be ideal.

**Comment by osmarks** [comment]
Can you elaborate on this? Their released code doesn't work at all in `legacy` mode and otherwise fails with various errors given several of the Argos HDF5 files.
