### ISSUE TITLE
关于预训练模型与论文一致性的疑问

### ISSUE THREAD

**Issue by Catmas06** [mobicom24/RF-Diffusion#6]
感谢您的开源，以下是我关于论文和代码的一些疑问(具体为fmcw相关模块)：
1、我注意到您在训练过程中计算的MSE loss是当前的predict与data的loss，即x_t与x_0的MSE loss，与论文中的描述不太相同。论文中介绍您计算的是x_t与x_t-1的loss
2、在采样过程中您的代码调用的是native sampling，这在您论文中没有提到。我尝试使用您论文中描述的常规sampling 方式，发现生成结果并不好，这个结果与您的训练过程相对应，可能是我的理解或方法有问题，希望能得到您的解答
3、在我的理解中，论文中提到的ADB模块是对应代码中的DIA模块，但是论文中提到的Hierarchical Diffusion我未在代码中找到。您发布的代码中(不包含注释掉的代码)只是将DIA重复了n次，想知道是否您有其他的设计。
4、关于论文中的Hierarchical Diffusion的Denoise切片问题，请问您使用的fmcw参数是否为一个chirp512个采样点，一共128个chirp组成一个序列，即512 * 128的矩阵。想知道您切片的具体方式，是按照独立的chirp切，将几个独立的chirp分到一个组内，一共N组，每组为【512 * chirp数】；还是将所有chirp相应的几个采样点分为一组，一共分为N组，每组为【采样点个数 * 128】
5、想知道您是否有与论文相同的结构的预训练模型，或者是否有更详细的代码使用说明

再次感谢您的开源代码及优秀论文，期待您的回答

**Comment by Guoxuan-Chi** [comment]
@Catmas06 您好，感谢您对我们工作的关注！
1. 同经典的Diffusion理论一样，我们的神经网络模型是将x_t作为输入，推断得到\mu_{t-1}，并进一步采样得到x_{t-1}，这可以参考论文中的Figure 2和Figure 3。考虑到Diffusion理论（包括RF-Diffusion）中添加的噪声都是0均值的，因此，大部分现有的工作（包括RF-Diffusion）在实际训练过程中，都是通过拟合x_0来实现拟合\mu_{t-1}的目标；
2. 为了便于感兴趣的老师同学们能够快速验证模型整体的可用性，避免过大的计算资源开销，我们提供的预训练模型设置了较少的diffusion steps，同时降低了模型的复杂度。代码中的DiA即为文章中提到的ADB，您可以参考论文中的设计或者按照自己的理解适当增加模块、修改diffusion steps、尝试不同的sampling策略；
3. 根据你的描述，在FMCW采样中，每个chirp中的512个采样点本质上包含的是空间信息（因为对512个采样点作FFT应当可以获取空间中不同反射物的距离），而128个chirp采样则包含了时序信息。因此，根据Hierarchical Diffusion中“先空间去噪，再时序去模糊“的设计，应当首先独立处理每个chirp（512个采样），再处理128个样本整体；

**Comment by Guoxuan-Chi** [comment]
@cc1300386495 您好，感谢您对我们工作的关注！
按照论文中的配置，我们的模型在8 * 3090显卡上进行训练，在初始化良好、超参数选取合适的情况下，12h~24h即可充分收敛。
我们提供了简化的预训练模型以供初步验证，该预训练模型支持在CPU或者单张普通桌面级GPU上进行推理（inference）。
